INSERT INTO Breweries(name, location, est, history, description) VALUES ('Carlsberg', 'Denmark', 1847, 'When his father died in 1835, J.C. Jacobsen took over his small brewery in Inner Copenhagen. Eventually, he decided he needed a new brewery with larger cool storage space. Therefore, he built a new brewery just outside Copenhagen, on top of a hill, where water was flowing.', 'The area surrounding Old Carlsberg is so central to our legacy and history that we owe our ancestors to maintain the heritage site and improve the experience for our guests. Our vision is to turn Carlsberg’s home into an inspiring and innovative place, where we can welcome guests and business partners.'); 
INSERT INTO Breweries(name, location, est, history, description) VALUES ('Svaneke', 'Denmark', 2000, 'Known for its beautiful landscapes, sunny weather and local delicacies and food producers, the small, rocky island of Bornholm is also the home of one of Denmark’s first microbreweries. Founded by a local beer enthusiast in 2000, Svaneke brewery and restaurant has developed into a successful local enterprise. But the original respect for and connection to the craft are still intact.', 'Svaneke Bryghus is a 100% organic brewery. As one of the first microbreweries to open in Denmark, Svaneke Bryghus on Bornholm is today widely known for its authentic taste, sustainable production methods and wide range of craft beers.'); 
INSERT INTO Breweries(name, location, est, history, description) VALUES ('Heineken', 'Netherlands', 1863, 'Gerard Adriaan Heineken is born into an Amsterdam merchant family in 1841. In 1864 he buys brewery ‘De Hooiberg’ (The Haystack) in Amsterdam and immediately turns his focus towards brewing uncompromised premium lager beer. He embraces the latest brewing innovations and becomes the first brewer on the planet to introduce a quality control lab. He also did a lot for the city of Amsterdam.', 'Heineken NV (Heineken) is a brewing company that develops, markets, and sells alcoholic beverages. The companys product portfolio comprises beer, cider, soft drinks and other beverages.'); 
INSERT INTO Breweries(name, location, est, history, description) VALUES ('Guinness', 'Ireland', 1759, 'It takes a thirst for adventure to do things the Guinness way. From our humble beginnings in 1759 to the present day, weve gone to extraordinary lengths to bring you exceptional beer. But were not ones to rest on our laurels. As we like to put it: our greatest work is yet to come.', 'From the original black stuff to its alcohol-free comrade, weve covered all bases when it comes to beer. Were constantly innovating to bring you new ways to enjoy one of the worlds oldest and most loved drinks, and we won’t settle for anything less than perfection.'); 
INSERT INTO Breweries(name, location, est, history, description) VALUES ('Erdinger', 'Germany', 1886, 'For over 130 years, the outstanding quality of our wheat beers has been rooted in our passion for Bavarian brewing skills. As a private brewery, we stand for', 'As a traditional brewery, we make no compromises when it comes to quality. A highly perfected product which is strictly brewed according to the Bavarian Purity Law. The finest wheat and barley malt, together with selected hops and crystal-clear water from our own deep wells, are just part of the genuine wheat beer flavour. '); 
INSERT INTO Breweries(name, location, est, history, description) VALUES ('Mikkeller', 'Denmark', 2006, 'Mikkeller er et dansk mikrobryggeri. Bryggeriet blev grundlagt af Mikkel Borg Bjergsø og Kristian Klarup Keller i 2006. Fra 2007 blev det drevet af Mikkel Borg Bjergsø alene. Samme år blev det kåret som årets danske mikrobryggeri af Danske Ølentusiaster.', 'Can include hops, malt, barrel aging, spontaneous fermentation, coffee, passion fruit, cherries, chilli, yuzu, chocolate and more.'); 



INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Guinness Draught', 'Stout', 4.2, 'Water, Barley, Hops, Yeast', 'Guinness Draught is a classic Irish stout with a smooth and creamy texture. It features a rich, dark color and a velvety head. The flavor profile includes notes of roasted malt, coffee, and dark chocolate.', 'Heineken');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Guinness Foreign Extra Stout', 'Stout', 7.5, 'Water, Barley, Hops, Yeast', 'Guinness Foreign Extra Stout is a stronger and more robust version of the traditional Guinness stout. It has a higher alcohol content and a bolder flavor profile. The beer showcases complex notes of roasted grains, caramel, and dark fruits.', 'Heineken');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Heineken Lager', 'Pale Lager', 5.0, 'Water, Barley, Hops, Yeast', 'Heineken Lager is a well-known pale lager with a light golden color and a crisp, refreshing taste. It has a balanced flavor profile with subtle notes of hops and malt, offering a smooth and clean finish.', 'Heineken');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Heineken 0.0', 'Non-Alcoholic', 0.0, 'Water, Barley, Hops, Yeast', 'Heineken 0.0 is a non-alcoholic version of the classic Heineken Lager. It offers the same distinct flavor and characteristics as the original, but with zero alcohol content. Its a refreshing and satisfying option for those seeking a non-alcoholic beer.', 'Heineken');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Erdinger Weissbier', 'Hefeweizen', 5.3, 'Water, Wheat, Barley, Hops, Yeast', 'Erdinger Weissbier is a classic German wheat beer with a cloudy appearance and a refreshing taste. It features a balanced combination of fruity and spicy flavors, with hints of banana, clove, and citrus. This unfiltered beer has a smooth and creamy texture.', 'Erdinger');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Erdinger Dunkel', 'Dunkelweizen', 5.6, 'Water, Wheat, Barley, Hops, Yeast', 'Erdinger Dunkel is a dark wheat beer that combines the rich maltiness of a traditional German dunkel with the smoothness of a wheat beer. It has a deep amber color and a complex flavor profile with notes of caramel, chocolate, and roasted grains. The beer has a medium body and a slightly spicy finish.', 'Erdinger');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Carlsberg Pilsner', 'Pilsner', 5.0, 'Water, Barley, Hops, Yeast', 'Carlsberg Pilsner is a classic Danish pilsner with a golden color and a crisp, clean taste. It offers a well-balanced flavor profile with a slightly bitter hop character and a smooth finish.', 'Carlsberg');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Carlsberg Elephant', 'Strong Lager', 7.2, 'Water, Barley, Hops, Yeast', 'Carlsberg Elephant is a strong lager known for its robust flavor and higher alcohol content. It has a deep golden color and a rich, malty taste with hints of caramel and a slightly sweet finish.', 'Carlsberg');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Carlsberg Smooth Draught', 'Lager', 4.8, 'Water, Barley, Hops, Yeast', 'Carlsberg Smooth Draught is a smooth and easy-drinking lager. It features a light and refreshing taste with a mild bitterness. The beer is known for its unique "pop cap" that enhances the smooth pouring experience.', 'Carlsberg');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Carlsberg Special Brew', 'Malt Liquor', 7.5, 'Water, Barley, Hops, Yeast', 'Carlsberg Special Brew is a strong malt liquor known for its full-bodied flavor and higher alcohol content. It has a rich malt profile with a slightly sweet and fruity character, offering a warming sensation.', 'Carlsberg');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Carlsberg 0.0', 'Non-Alcoholic', 0.0, 'Water, Barley, Hops, Yeast', 'Carlsberg 0.0 is a non-alcoholic version of the classic Carlsberg Pilsner. It delivers the same crisp and refreshing taste but without the alcohol. Its a suitable choice for those seeking a non-alcoholic beer option.', 'Carlsberg');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Mikkeller Beer Geek Breakfast', 'Imperial Stout', 7.5, 'Water, Barley, Hops, Yeast, Coffee, Oats', 'Mikkeller Beer Geek Breakfast is an imperial stout brewed with coffee and oats. It features a rich and full-bodied flavor with prominent notes of roasted malt, dark chocolate, and a strong coffee presence. This beer provides a balanced combination of bitterness and sweetness.', 'Mikkeller');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Mikkeller Windy Hill', 'IPA', 6.0, 'Water, Barley, Hops, Yeast', 'Mikkeller Windy Hill is an IPA (India Pale Ale) characterized by its hop-forward flavor profile. It showcases a blend of citrusy and tropical hop notes with a balanced bitterness. The beer has a crisp and refreshing taste, making it a popular choice among IPA enthusiasts.', 'Mikkeller');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Svaneke Himmelblå', 'Wheat Beer', 4.7, 'Water, Wheat, Barley, Hops, Yeast', 'Svaneke Himmelblå is a wheat beer known for its refreshing and light character. It has a hazy golden appearance and a fruity aroma. The beer offers a delicate balance of wheat malt sweetness and mild hop bitterness, resulting in a smooth and enjoyable drinking experience.', 'Svaneke');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('Svaneke Bock', 'Bock', 6.0, 'Water, Barley, Hops, Yeast', 'Svaneke Bock is a traditional bock beer with a rich and malty flavor profile. It features a deep amber color and a smooth, full-bodied taste. This beer offers a combination of caramel and toffee-like sweetness with a subtle hop presence, resulting in a satisfying and robust brew.', 'Svaneke');
INSERT INTO Beers(name, type, alc, pri_ing, description, brewery) VALUES ('KOM NU LIDT', 'ASD', 5.0, 'A,A,A','aasd', 'Carlsberg');